name: Process Text Files

on:
  push:
    branches: [ main ]

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "NAME=Burhan" >> $GITHUB_ENV

          # Calculate sum from Numbers.txt
          echo "FILE_SUM=$(awk -F'[ ,]+' '{for(i=1;i<=NF;i++) if($i~/^[0-9]+$/) s+=$i} END{print s}' Numbers.txt)" >> $GITHUB_ENV

      - name: Replace {{name}} in name.txt
        run: |
          sed -i "s/{{name}}/${NAME}/g" name.txt
        env:
          NAME: ${{ env.NAME }}

      - name: Replace {{sum}} in Numbers.txt
        run: |
          sed -i "s/{{sum}}/${FILE_SUM}/g" Numbers.txt
        env:
          FILE_SUM: ${{ env.FILE_SUM }}

      - name: Show output files
        run: |
          echo "----- name.txt -----"
          cat name.txt
          echo "----- Numbers.txt -----"
          cat Numbers.txt
